// <auto-generated />
using System;
using Database_Connection.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database_Connection.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241222192345_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Database_Connection.Models.University.Course", b =>
                {
                    b.Property<int>("Cour_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cour_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Cour_id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Database_Connection.Models.University.Student", b =>
                {
                    b.Property<int>("Stu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Stu_Cour_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Stu_bdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Stu_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stu_gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stu_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stu_place")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Stu_id");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
